### PR TITLE
Adds Particles to background

### PR DESCRIPTION
**Pull request by benjaminjkamp**
DOM sometimes stays within, sometimes gets pushed down below particles..

### CODE REVIEW

**Comment by benmfoster** [comment]
Can you list the packages you installed so I can run this locally?

**Comment by benjaminjkamp** [comment]
npm install react-particles-js

**Comment by benmfoster** [comment]
thanks

**Comment by benmfoster** [comment]
Can we remove interact.js and Stats.js from this request? Also what are we doing with the commented out code? If it's for reference can we move it to a text file?

**Comment by benmfoster** [comment]
I commented out line 146 and it fixed the DOM issue.

vertical-align isn't doing anything in App.css for canvas

Add position:absolute;bottom:0; to canvas in App.css to get rid of the blank margin on the bottom of the page.

Those are all the changes I would like to see. Otherwise this is dope, lots of manipulable JavaScript here to play around with.

**Comment by benjaminjkamp** [comment]
cleared index.css as it was conflicting with particle customization, deleted all the commented/test code from vex and stats, etc. removed the extra particle object (146), added the suggested css to canvas, but commented out as it makes the DOM unusable currently. Customized the particle appearance and changed from that god awful red to a nice soothing dark blue

**Pull request merged**
